# @package _global_

data:
  root_dir: ./data
  train_dir: ""
  remove_whitespace: false
  normalize_unicode: false

model:
  max_label_length: 2
  batch_size: 32

trainer:
  max_epochs: 30
  devices: 1
  val_check_interval: 5
